---
title: "Microbiome_baseline"
format: docx
editor: visual
bibliography: references.bib
---

## Abstract

Pollinators are essential for both natural and agricultural systems, supporting the the diversity of plant communities and the productivity of crops around the globe. However, different global change drivers increasingly threaten these pollinator populations, leading to declines in population numbers and cascading effects on ecosystems and human food security. One critical but understudied aspect of pollinator health is their microbiome. The microbiome, a community of microorganisms living within and on pollinators, plays a significant role in digestion, immune function, and disease resistance, amongst others. However, environmental changes and pesticide exposure can disrupt these microbial communities, compromising pollinator health and survival. Most research on pollinator microbiomes has focused on managed species like honeybees, leaving significant gaps in our understanding of wild pollinators. This study investigates the microbiome composition of the common carder bee (*Bombus pascuorum*) across different floral environments throughout the flowering season. By analyzing the gut microbiomes of these bees, we aim to uncover how environmental factors shape their microbial communities, providing crucial insights into their resilience and adaptability in the face of global change. This knowledge is essential for guiding conservation efforts to protect pollinator populations.

## Introduction

Pollinators play a critical role in the functioning of both natural and agricultural systems worldwide, facilitating the reproduction of \>85% of flowering plants [@ollerton2011] and contributing to the production of \>75% of global food crops [@klein2006]. However, pollinators are increasingly at risk due to multiple global change drivers, something that has been recently defined as "death by a thousand cuts" [@wagner2021]. Climate change, with its impacts on temperature and precipitation patterns, disrupts pollinator behaviors and/or morphologies [@miller-struttmann2015] leading to plant-pollinator mismatches [@gérard2020]. Habitat loss and fragmentation lead to a reduction in pollinator populations [@winfree2009], while the widespread use of pesticides introduce additional stresses [@guzman2024]. These factors, compounded by the spread of diseases [@manley2015] and the increasing presence of invasive species [@vanbergen2017], threaten the survival of pollinator populations, leading to cascading effects on ecosystems and human food systems [@devkota2024; @murphy2022].

A relatively unexplored yet crucial aspect of pollinator populations is their microbiome [@shah2024], the community of microorganisms living within and on them. The microbiome can significantly impact the health, physiology [@Engel2013], development, and survival [@ferguson2018] of organisms, influencing digestion, immune function, and disease resistance. In insect pollinators, the gut microbiome plays a vital role in nutrient absorption [@zheng2017; @zheng2019], detoxification of harmful substances [@engel2012], and protection against pathogens [@steele2021; @koch2011]. Disruptions to the microbiome, whether through environmental changes, pesticide exposure, or other stressors, can compromise these essential functions and lead to increased vulnerability and mortality [@maes2016]. Understanding the composition and functionality of microbiomes is therefore critical, not only for gaining insights into the biology and ecology of pollinator species but also for developing strategies to mitigate the adverse effects of global change drivers.

Most research on pollinator microbiomes has focused on managed species, like honeybees [@engel2012] and certain bumblebee species [@weinhold2024], providing valuable insights into their gut microbial communities and how these microorganisms influence their health and productivity. However, our understanding of the microbiomes of other pollinator species, and particularly of wild species, remains limited (although see [@li2023] for a focus on other species). We know even less about how these microbiomes change over time or how different environmental factors shape them. As global change continues to alter ecosystems, understanding the temporal and spatial dynamics of pollinator microbiomes could provide valuable insights into how these species might cope with environmental stresses, maintain ecosystem functions, and contribute to biodiversity conservation.

Research in honeybees and some bumblebees has shown the existence of a core microbiome in these species, defined as a common group of microbes that are found across individuals of a given species (although the existence of this core microbiome is still somewhat controversial [@risely2020; @neu2021]. This core microbiome consists of around five genera in the case of honeybees [@carlini2024] and is mostly vertically-transmitted within the hive [@martinson2010]. In addition to this core microbiome, pollinators also acquire microbes from their environment, particularly through their diet [@ludvigsen2015], which can include nectar, pollen, and other floral resources. These acquired microorganisms can introduce new functions and adaptations but also make pollinators susceptible to environmental changes and stressors, which raises the need to understand the relationship between landscape composition (e.g., floral diversity) and microbiome composition.

Here, we focus on understanding the microbiome composition and dynamics of a wild pollinator species, the common carder bee (*Bombus pascuorum*), throughout the flowering season and across different sites that vary in floral diversity. By analyzing the gut microbiomes of these bees, we aim to uncover how the diversity and abundance of flower species in their environment influence the microbial communities they harbor. This study sheds light on the temporal changes in microbiome composition within *B. pascuorum* and reveals how different ecological contexts shape these vital microbial communities. Our findings contribute to a deeper understanding of the ecological interactions between wild pollinators and their environments, providing insights that are essential for conservation efforts and the maintenance of healthy pollinator populations.

## Methods

Our study was conducted within Gorbeia Natural Park, a protected area located in the Basque Country in N Spain. The region is shaped by the Atlantic Ocean's influence, resulting in mild winters and summers, alongside high annual rainfall, averaging around 1300 mm. During the study period (April to July), the average temperatures range from 10°C to 17.5°C [@Pizarro2021]. The area's vegetation includes beech forests mixed with extensive conifer plantations. Additionally, there is a notable presence of shrubland and meadows, particularly in the rockier, steeper regions of the mountain [@Albizu2002COMPARACINDL].

Within the park, we selected 16 different sampling sites, all of them located at similar altitudes \~800 m a.s.l, which we sampled every two weeks depending on weather conditions, avoiding rainy, windy or foggy days. At every sampling date we aimed to collect at least 5 *B. pascuorum* individuals per day, although this was not always possible. All collected individuals were labeled and stored independently in 50 ml vials at -20ºC until processed in the laboratory. For each bumblebee specimen we measured the inter-tegular distance as a measure of body size [@stemet2024]. We then extracted bumblebee guts using sterile forceps which we stored in 96% alcohol until the DNA extraction. Bacterial, plant and fungi DNA was extracted following Macherey-Nagel NucleoSpin® 96 Soil protocol (2021) and were  amplified in duplicate using the DFD forward and ASDFAS reverse primers.

To avoid site and period vias all samples were randomized using a randomizer program before the DNA extraction, creating a new individual code for each sample.

DNA Extraction and PCR Amplification

Each gut sample was placed in a separate 2 mL vial with ceramic beads, and the ethanol was allowed to evaporate. Once dry, 700 µL of Lysis Buffer (SL1) were added to each vial, and the samples were mechanically homogenized (1750 rpm for 1 min with 15 s pauses, repeated 5 times). Contaminants were removed via precipitation, followed by centrifugation at 11,000 × g for 2 minutes to eliminate foam. Next, 150 µL of Buffer SL3 were added to each sample, vortexed for 5 seconds, and incubated on ice at 0-4ºC for 5 minutes, followed by centrifugation at 11,000 × g for 1 minute.

The lysate was filtered using a square-well block and the NucleoSpin® Inhibitor Removal Plate. 550 µL of the clear supernatant was loaded into each well, and the plates were centrifuged at 2,250 × g for 13 minutes. The NucleoSpin® Inhibitor Removal Plate was discarded, and 250 µL of Buffer SB was added to the flow-through, mixed by pipetting.

To bind the DNA, 725 µL of sample was transferred to a NucleoSpin® Soil Binding Plate and centrifuged at 2,250 × g for 13 minutes. The flow-through was discarded. DNA was washed in four steps: (1) 500 µL of Buffer SB, centrifuged at 2,250 × g for 13 minutes; (2) 550 µL of Buffer SW1, centrifuged at 2,250 × g for 5 minutes; (3) 700 µL of Buffer SW2, centrifuged at 2,250 × g for 5 minutes; (4) 700 µL of Buffer SW2, centrifuged at 2,250 × g for 13 minutes. After washing, the plate was incubated at 37ºC for 20 minutes to dry the silica membrane.

DNA was eluted by adding 100 µL of Buffer SE to each well, incubating for 1 minute, and centrifuging at 2,250 × g for 5 minutes. A total of 132 samples were obtained, with each sample labeled accordingly. Nanodrop tests were performed on random samples to confirm successful DNA extraction.

PCR Amplification

DNA amplification was assessed using two-step PCR. Step 1 PCRs were performed for bacterial, plant, and fungal genetic material, with identical reagent volumes for all samples, differing only in the primers used (Table xxx). PCRs were run in a 96-well plate, with two plates for each group: one containing 96 samples and another with 40 samples, including negative controls. Step 1 PCR was repeated twice per sample, after which 7.5 µL from each replicate were pooled into a new plate, with 15 µL per well. PCR amplification success was confirmed via 2% agarose gel electrophoresis between Step 1 and Step 2 PCRs to verify amplicon size.

## Results

During the 2023 season, we collected a total of 132 bumblebee specimens.

## Discussion

## References
